let
    Source = Excel.Workbook(File.Contents("C:\Users\zinnickj\OneDrive - MyFedEx\Desktop\Inquest Yields\RAW Data.xlsx"), null, true),
    #"LextEdit Export 05-31-21 22.58_Sheet" = Source{[Item="LextEdit Export 06-07-21 09.47",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"LextEdit Export 05-31-21 22.58_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"rmaact_id", type text}, {"dtlnum", type text}, {"rmanum", type text}, {"client_id", type text}, {"rmaprt", type text}, {"rcvprt", type text}, {"prtnum", type text}, {"rcvsts", type text}, {"retcod", type text}, {"rtnrsncod", type text}, {"bldg_id", type text}, {"arecod", type text}, {"stoloc", type text}, {"wh_id", type text}, {"adddte", type datetime}, {"mod_usr_id", type text}, {"rmatyp", type text}, {"sales_channel", type text}, {"ordnum", type text}, {"devcod", type text}, {"prtfam", type text}, {"untcst", type number}, {"uc_supplier", Int64.Type}, {"uc_make", type text}, {"uc_model", type text}, {"uc_family", type text}, {"uc_subfam", type text}, {"colval", type text}, {"lngdsc", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"client_id", "rmaprt", "rcvprt", "prtnum", "rcvsts", "bldg_id", "arecod", "wh_id", "mod_usr_id", "rmatyp", "sales_channel", "ordnum", "prtfam", "uc_supplier", "uc_family", "uc_subfam", "colval", "uc_model"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"untcst", Currency.Type}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type2",{{"adddte", type date}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type1", "lngdsc", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"lngdsc.1", "lngdsc.2", "lngdsc.3", "lngdsc.4", "lngdsc.5"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"lngdsc.1", type text}, {"lngdsc.2", type text}, {"lngdsc.3", type text}, {"lngdsc.4", type text}, {"lngdsc.5", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type3",{"lngdsc.1", "lngdsc.2", "lngdsc.5"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns1","IPH","IPHONE",Replacer.ReplaceValue,{"lngdsc.3"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","IPHN","IPHONE",Replacer.ReplaceText,{"lngdsc.3"}),
    #"Merged Columns" = Table.CombineColumns(#"Replaced Value1",{"lngdsc.3", "lngdsc.4"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"WMS Model"),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Merged Columns", {{"WMS Model", each Text.BeforeDelimiter(_, "SMG"), type text}}),
    #"Extracted Text Before Delimiter2" = Table.TransformColumns(#"Extracted Text Before Delimiter", {{"WMS Model", each Text.BeforeDelimiter(_, "ACTIV"), type text}}),
    #"Extracted Text Before Delimiter3" = Table.TransformColumns(#"Extracted Text Before Delimiter2", {{"WMS Model", each Text.BeforeDelimiter(_, "SMN"), type text}}),
    #"Extracted Text Before Delimiter11" = Table.TransformColumns(#"Extracted Text Before Delimiter3", {{"WMS Model", each Text.BeforeDelimiter(_, "16G"), type text}}),
    #"Extracted Text Before Delimiter1" = Table.TransformColumns(#"Extracted Text Before Delimiter11", {{"WMS Model", each Text.BeforeDelimiter(_, "32G"), type text}}),
    #"Extracted Text Before Delimiter4" = Table.TransformColumns(#"Extracted Text Before Delimiter1", {{"WMS Model", each Text.BeforeDelimiter(_, "64G"), type text}}),
    #"Extracted Text Before Delimiter5" = Table.TransformColumns(#"Extracted Text Before Delimiter4", {{"WMS Model", each Text.BeforeDelimiter(_, "128G"), type text}}),
    #"Extracted Text Before Delimiter6" = Table.TransformColumns(#"Extracted Text Before Delimiter5", {{"WMS Model", each Text.BeforeDelimiter(_, "256G"), type text}}),
    #"Extracted Text Before Delimiter10" = Table.TransformColumns(#"Extracted Text Before Delimiter6", {{"WMS Model", each Text.BeforeDelimiter(_, "512G"), type text}}),
    #"Extracted Text Before Delimiter12" = Table.TransformColumns(#"Extracted Text Before Delimiter10", {{"WMS Model", each Text.BeforeDelimiter(_, "128"), type text}}),
    #"Extracted Text Before Delimiter13" = Table.TransformColumns(#"Extracted Text Before Delimiter12", {{"WMS Model", each Text.BeforeDelimiter(_, "256"), type text}}),
    #"Extracted Text Before Delimiter14" = Table.TransformColumns(#"Extracted Text Before Delimiter13", {{"WMS Model", each Text.BeforeDelimiter(_, "512"), type text}}),
    #"Extracted Text Before Delimiter7" = Table.TransformColumns(#"Extracted Text Before Delimiter14", {{"WMS Model", each Text.BeforeDelimiter(_, "SMA"), type text}}),
    #"Extracted Text Before Delimiter8" = Table.TransformColumns(#"Extracted Text Before Delimiter7", {{"WMS Model", each Text.BeforeDelimiter(_, "SMF"), type text}}),
    #"Extracted Text Before Delimiter9" = Table.TransformColumns(#"Extracted Text Before Delimiter8", {{"WMS Model", each Text.BeforeDelimiter(_, "THINQ"), type text}}),
    #"Extracted Text Before Delimiter15" = Table.TransformColumns(#"Extracted Text Before Delimiter9", {{"WMS Model", each Text.BeforeDelimiter(_, "LMG"), type text}}),
    #"Extracted Text Before Delimiter16" = Table.TransformColumns(#"Extracted Text Before Delimiter15", {{"WMS Model", each Text.BeforeDelimiter(_, "LMF"), type text}}),
    #"Extracted Text Before Delimiter17" = Table.TransformColumns(#"Extracted Text Before Delimiter16", {{"WMS Model", each Text.BeforeDelimiter(_, "EDGE"), type text}}),
    #"Extracted Text Before Delimiter18" = Table.TransformColumns(#"Extracted Text Before Delimiter17", {{"WMS Model", each Text.BeforeDelimiter(_, "S4"), type text}}),
    #"Extracted Text Before Delimiter19" = Table.TransformColumns(#"Extracted Text Before Delimiter18", {{"WMS Model", each Text.BeforeDelimiter(_, "2018"), type text}}),
    #"Extracted Text Before Delimiter20" = Table.TransformColumns(#"Extracted Text Before Delimiter19", {{"WMS Model", each Text.BeforeDelimiter(_, "2017"), type text}}),
    #"Extracted Text Before Delimiter21" = Table.TransformColumns(#"Extracted Text Before Delimiter20", {{"WMS Model", each Text.BeforeDelimiter(_, "5G"), type text}}),
    #"Extracted Text Before Delimiter22" = Table.TransformColumns(#"Extracted Text Before Delimiter21", {{"WMS Model", each Text.BeforeDelimiter(_, "1TB"), type text}}),
    #"Extracted Text Before Delimiter23" = Table.TransformColumns(#"Extracted Text Before Delimiter22", {{"WMS Model", each Text.BeforeDelimiter(_, "XP38"), type text}}),
    #"Extracted Text Before Delimiter24" = Table.TransformColumns(#"Extracted Text Before Delimiter23", {{"WMS Model", each Text.BeforeDelimiter(_, "XP88"), type text}}),
    #"Extracted Text Before Delimiter25" = Table.TransformColumns(#"Extracted Text Before Delimiter24", {{"WMS Model", each Text.BeforeDelimiter(_, "U102AA"), type text}}),
    #"Replaced Value3" = Table.ReplaceValue(#"Extracted Text Before Delimiter25","SE16","SE",Replacer.ReplaceText,{"WMS Model"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","SE20","SE",Replacer.ReplaceText,{"WMS Model"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","SE20X","SE",Replacer.ReplaceText,{"WMS Model"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","SEX","SE",Replacer.ReplaceText,{"WMS Model"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value6"," ","",Replacer.ReplaceText,{"WMS Model"})
in
    #"Replaced Value2"